/**
 * ⚙️ AUTO-GENERATED REGISTRY
 * DO NOT EDIT THIS FILE MANUALLY. Updated by scripts/generate-registry.mjs
 */

import { AddToCartButton } from './components/AddToCartButton/AddToCartButton';
import { CardWrapper } from './components/CardWrapper';
import { CartBadge } from './components/CartBadge/CartBadge';
import { CanvasBento } from './components/Elements/CanvasBento';
import { CanvasButton } from './components/Elements/CanvasButton';
import { CanvasCheckbox } from './components/Elements/CanvasCheckbox';
import { CanvasHeader } from './components/Elements/CanvasHeader';
import { CanvasInput } from './components/Elements/CanvasInput';
import { CanvasLayout } from './components/Elements/CanvasLayout';
import { CanvasSwitch } from './components/Elements/CanvasSwitch';
import { CanvasText } from './components/Elements/CanvasText';
import { Footer } from './components/Footer/Footer';
import { Hero } from './components/Hero/Hero';
import { HeroSubtitle } from './components/Hero/HeroSubtitle';
import { HeroTitle } from './components/Hero/HeroTitle';
import { Navbar } from './components/Navbar';
import { Button } from './components/Primitives/Actions/Button';
import { Toggle } from './components/Primitives/Actions/Toggle';
import { ToggleGroup } from './components/Primitives/Actions/ToggleGroup';
import { Avatar } from './components/Primitives/DataDisplay/Avatar';
import { Badge } from './components/Primitives/DataDisplay/Badge';
import { Card } from './components/Primitives/DataDisplay/Card';
import { Table } from './components/Primitives/DataDisplay/Table';
import { Checkbox } from './components/Primitives/Inputs/Checkbox';
import { Combobox } from './components/Primitives/Inputs/Combobox';
import { Form } from './components/Primitives/Inputs/Form';
import { Input } from './components/Primitives/Inputs/Input';
import { RadioGroup } from './components/Primitives/Inputs/RadioGroup';
import { Select } from './components/Primitives/Inputs/Select';
import { Slider } from './components/Primitives/Inputs/Slider';
import { Switch } from './components/Primitives/Inputs/Switch';
import { Textarea } from './components/Primitives/Inputs/Textarea';
import { FooterBar } from './components/Primitives/Layout/FooterBar';
import { Heading } from './components/Primitives/Layout/Heading';
import { ImagePlaceholder } from './components/Primitives/Layout/ImagePlaceholder';
import { LayoutBox } from './components/Primitives/Layout/LayoutBox';
import { Link } from './components/Primitives/Layout/Link';
import { NavBar } from './components/Primitives/Layout/NavBar';
import { Paragraph } from './components/Primitives/Layout/Paragraph';
import { Section } from './components/Primitives/Layout/Section';
import { Separator } from './components/Primitives/Layout/Separator';
import { Breadcrumb } from './components/Primitives/Navigation/Breadcrumb';
import { Pagination } from './components/Primitives/Navigation/Pagination';
import { AlertDialog } from './components/Primitives/Overlays/AlertDialog';
import { Toast } from './components/Primitives/Overlays/Toast';
import { Tooltip } from './components/Primitives/Overlays/Tooltip';
import { Accordion } from './components/Primitives/Structure/Accordion';
import { Collapsible } from './components/Primitives/Structure/Collapsible';
import { ContextMenu } from './components/Primitives/Structure/ContextMenu';
import { Dialog } from './components/Primitives/Structure/Dialog';
import { DropdownMenu } from './components/Primitives/Structure/DropdownMenu';
import { HoverCard } from './components/Primitives/Structure/HoverCard';
import { Menubar } from './components/Primitives/Structure/Menubar';
import { NavigationMenu } from './components/Primitives/Structure/NavigationMenu';
import { Popover } from './components/Primitives/Structure/Popover';
import { Sheet } from './components/Primitives/Structure/Sheet';
import { Tabs } from './components/Primitives/Structure/Tabs';
import { Text } from './components/Text';

export interface RemoteComponentProp {
  name: string;
  label: string;
  type: "string" | "number" | "boolean" | "color" | "select";
  options?: string[]; 
  defaultValue?: any;
}

export interface RemoteComponentMeta {
  type: string;
  name: string;
  version: string;
  description?: string;
  category?: string;
  isPremium?: boolean;
  isSlot?: boolean;
  parentConstraint?: string | string[];
  propControls: RemoteComponentProp[];
  dependencies?: Record<string, string>;
}

const componentRegistry: Record<string, { exportName: string; meta: RemoteComponentMeta }> = {
  "ui_atc_button": { exportName: "AddToCartButton", meta: (AddToCartButton as any).meta },
  "ui_card_wrapper": { exportName: "CardWrapper", meta: (CardWrapper as any).meta },
  "ui_cart_badge": { exportName: "CartBadge", meta: (CartBadge as any).meta },
  "ui_canvas_bento": { exportName: "CanvasBento", meta: (CanvasBento as any).meta },
  "ui_canvas_button": { exportName: "CanvasButton", meta: (CanvasButton as any).meta },
  "ui_canvas_checkbox": { exportName: "CanvasCheckbox", meta: (CanvasCheckbox as any).meta },
  "ui_canvas_header": { exportName: "CanvasHeader", meta: (CanvasHeader as any).meta },
  "ui_canvas_input": { exportName: "CanvasInput", meta: (CanvasInput as any).meta },
  "ui_canvas_layout": { exportName: "CanvasLayout", meta: (CanvasLayout as any).meta },
  "ui_canvas_switch": { exportName: "CanvasSwitch", meta: (CanvasSwitch as any).meta },
  "ui_canvas_text": { exportName: "CanvasText", meta: (CanvasText as any).meta },
  "ui_footer": { exportName: "Footer", meta: (Footer as any).meta },
  "ui_hero": { exportName: "Hero", meta: (Hero as any).meta },
  "ui_hero_subtitle": { exportName: "HeroSubtitle", meta: (HeroSubtitle as any).meta },
  "ui_hero_title": { exportName: "HeroTitle", meta: (HeroTitle as any).meta },
  "navbar": { exportName: "Navbar", meta: (Navbar as any).meta },
  "ui_shadcn_button": { exportName: "Button", meta: (Button as any).meta },
  "toggle": { exportName: "Toggle", meta: (Toggle as any).meta },
  "togglegroup": { exportName: "ToggleGroup", meta: (ToggleGroup as any).meta },
  "ui_shadcn_avatar": { exportName: "Avatar", meta: (Avatar as any).meta },
  "ui_shadcn_badge": { exportName: "Badge", meta: (Badge as any).meta },
  "ui_shadcn_card": { exportName: "Card", meta: (Card as any).meta },
  "table": { exportName: "Table", meta: (Table as any).meta },
  "ui_shadcn_checkbox": { exportName: "Checkbox", meta: (Checkbox as any).meta },
  "combobox": { exportName: "Combobox", meta: (Combobox as any).meta },
  "ui_shadcn_form": { exportName: "Form", meta: (Form as any).meta },
  "ui_shadcn_input": { exportName: "Input", meta: (Input as any).meta },
  "radiogroup": { exportName: "RadioGroup", meta: (RadioGroup as any).meta },
  "select": { exportName: "Select", meta: (Select as any).meta },
  "slider": { exportName: "Slider", meta: (Slider as any).meta },
  "switch": { exportName: "Switch", meta: (Switch as any).meta },
  "ui_shadcn_textarea": { exportName: "Textarea", meta: (Textarea as any).meta },
  "ui_shadcn_footer": { exportName: "FooterBar", meta: (FooterBar as any).meta },
  "ui_shadcn_heading": { exportName: "Heading", meta: (Heading as any).meta },
  "ui_shadcn_image": { exportName: "ImagePlaceholder", meta: (ImagePlaceholder as any).meta },
  "ui_shadcn_layout": { exportName: "LayoutBox", meta: (LayoutBox as any).meta },
  "ui_shadcn_link": { exportName: "Link", meta: (Link as any).meta },
  "ui_shadcn_navbar": { exportName: "NavBar", meta: (NavBar as any).meta },
  "ui_shadcn_paragraph": { exportName: "Paragraph", meta: (Paragraph as any).meta },
  "ui_shadcn_section": { exportName: "Section", meta: (Section as any).meta },
  "ui_shadcn_separator": { exportName: "Separator", meta: (Separator as any).meta },
  "breadcrumb": { exportName: "Breadcrumb", meta: (Breadcrumb as any).meta },
  "pagination": { exportName: "Pagination", meta: (Pagination as any).meta },
  "alertdialog": { exportName: "AlertDialog", meta: (AlertDialog as any).meta },
  "toast": { exportName: "Toast", meta: (Toast as any).meta },
  "tooltip": { exportName: "Tooltip", meta: (Tooltip as any).meta },
  "accordion": { exportName: "Accordion", meta: (Accordion as any).meta },
  "collapsible": { exportName: "Collapsible", meta: (Collapsible as any).meta },
  "contextmenu": { exportName: "ContextMenu", meta: (ContextMenu as any).meta },
  "dialog": { exportName: "Dialog", meta: (Dialog as any).meta },
  "dropdownmenu": { exportName: "DropdownMenu", meta: (DropdownMenu as any).meta },
  "hovercard": { exportName: "HoverCard", meta: (HoverCard as any).meta },
  "menubar": { exportName: "Menubar", meta: (Menubar as any).meta },
  "navigationmenu": { exportName: "NavigationMenu", meta: (NavigationMenu as any).meta },
  "popover": { exportName: "Popover", meta: (Popover as any).meta },
  "sheet": { exportName: "Sheet", meta: (Sheet as any).meta },
  "tabs": { exportName: "Tabs", meta: (Tabs as any).meta },
  "ui_text": { exportName: "Text", meta: (Text as any).meta }
};

export const getSafeCatalog = (pkgName: string, baseUrl: string = '/api/remote-asset') => {
  return Object.entries(componentRegistry).map(([regType, comp]: [string, any]) => {
    const meta = comp.meta || {};
    const isLocalApi = baseUrl.includes('/api/remote-asset');
    
    const finalType = meta.type || regType;

    const url = isLocalApi 
      ? `${baseUrl}?pkg=${encodeURIComponent(pkgName)}&comp=${encodeURIComponent(finalType)}&v=${meta.version}`
      : `${baseUrl}/${encodeURIComponent(pkgName)}/${meta.version}/${finalType}.js`;

    return {
      type: finalType,
      ...meta,
      url,
      importPath: pkgName,
      exportName: comp.exportName,
      isPremium: meta.isPremium === true
    };
  });
};
